apiVersion: v2
name: stocat-service
description: stocat application chart
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"

# Note: Optionally inject Consul host/port to all apps via values.global.consul.
