version: "3.8"
services:
  consul:
    image: hashicorp/consul:1.21.1
    command: agent -dev -ui -client=0.0.0.0 -log-level=INFO
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    restart: unless-stopped

  consul-init:
    image: curlimages/curl:latest
    depends_on:
      - consul
    volumes:
      - ./consul-config:/consul-config
      - ./consul-init.sh:/consul-init.sh
    entrypoint: ["/bin/sh", "/consul-init.sh"]
