nameOverride: demo-order

image:
  repository: demo-order
  tag: 0.0.1-SNAPSHOT

containerPort: 8082

service:
  enabled: true
  type: ClusterIP
  port: 8082

profiles:
  active: local-k8s

httpRoute:
  enabled: true
  parentRefs:
    - name: istio-ingressgateway
      namespace: istio-system
  hostnames:
    - stocat-demo-order.local
  pathPrefixes:
    - "/"
