spring:
  cloud:
    consul:
      host: consul-server.consul.svc.cluster.local
      port: 8500
      config:
        enabled: true
        format: YAML
        data-key: routes.yaml
        prefixes:
          - config
        fail-fast: true
        watch:
          enabled: true